name: mlops-bootcamp-team10
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - ipywidgets
  - jupyter
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - plotly
  - python-kaleido
  - scikit-learn
  - seaborn
  - scipy
  - statsmodels
  - ydata-profiling
  - yellowbrick
  - dvc
  - dvc-s3
  - pip:
      - python-dotenv
      - mkdocs
      - -e .
