name: mlops-bootcamp-team10
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - pip:
      - python-dotenv
      - mkdocs
      - -e .
